services:

  pg:
    container_name: fapi_pg
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: service
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    container_name: fapi_pgadmin
    image: dpage/pgadmin4
    ports:
      - "5435:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/pgadmin

volumes:
  pg_data:
  pgadmin_data: